// Bu dosya otomatik üretilir. Elle düzenleme; docs/METINLER.md dosyasını değiştirip `npm run metinler` çalıştır.
import type { KazaVakit } from './types';

export const METINLER = {
  "uygulama.ad": "Kaza Defteri",
  "genel.devam": "Devam et",
  "genel.kaydet": "Kaydet",
  "genel.vazgec": "Vazgeç",
  "genel.geriAl": "Geri al",
  "genel.tamam": "Tamam",
  "sekme.bugun": "Bugün",
  "sekme.vakitler": "Vakitler",
  "sekme.gecmis": "Geçmiş",
  "sekme.ayarlar": "Ayarlar",
  "kurulum.adim": "Kurulum, {n} / 3",
  "konum.baslik": "Vakitler için konumun",
  "konum.bul": "Konumumu bul",
  "konum.yaDa": "ya da listeden seç",
  "konum.ara": "İl veya ilçe ara",
  "konum.ilceler": "{il} ilçeleri",
  "konum.tumIller": "Tüm iller",
  "konum.gizlilik": "Konumun yalnızca namaz vakitlerini hesaplamak için telefonda kullanılır. Hiçbir yere gönderilmez.",
  "konum.gpsAdi": "Bulunduğun konum",
  "konum.hata": "Konum alınamadı. İlini listeden seçebilirsin.",
  "konum.secimYok": "Devam etmek için bir il seç.",
  "hesap.baslik": "Kaza borcunu hesapla",
  "hesap.yukumluluk": "Namazla yükümlü olduğun tarih (ergenlik)",
  "hesap.yukumlulukYardim": "Tam hatırlamıyorsan en yakın tahmini seç. Sonradan değiştirebilirsin.",
  "hesap.duzenli": "Düzenli kılmaya başladığın tarih",
  "hesap.henuzBaslamadim": "Henüz düzenli başlamadım",
  "hesap.mezhep": "Mezhep",
  "hesap.hanefi": "Hanefi",
  "hesap.safii": "Şafii",
  "hesap.ozelGun": "Özel günleri düş",
  "hesap.ozelGunAlt": "Kadın kullanıcılar için, ayda kaç gün",
  "hesap.ozelGunGiris": "Ayda ortalama gün",
  "hesap.formulBaslik": "Hesap nasıl yapıldı",
  "hesap.formulHanefi": "Her vakit için {gun} kaza: sabah, öğle, ikindi, akşam, yatsı ve vitir.",
  "hesap.formulSafii": "Her vakit için {gun} kaza: sabah, öğle, ikindi, akşam ve yatsı.",
  "hesap.formulDuzelt": "Sayıları istediğin zaman Ayarlar'dan tek tek düzeltebilirsin.",
  "hesap.uyari": "Hesap senin girdiğin bilgilere dayanır. Emin olmadığın durumlar için müftülüğe danışabilirsin.",
  "hesap.hataSira": "Başlangıç tarihi, düzenli kılmaya başladığın tarihten sonra olamaz.",
  "hesap.hataGelecek": "Gelecekteki bir tarih seçilemez.",
  "hesap.borcYok": "Bu bilgilere göre kaza borcun görünmüyor. Yine de günlük vakitleri takip edebilirsin.",
  "hatirlat.baslik": "Hatırlatmalar",
  "hatirlat.hangi": "Hangi vakitler için?",
  "hatirlat.yatsiAlt": "\"Kıldın mı?\" sorusu {saat}'te",
  "hatirlat.zaman": "\"Kıldın mı?\" ne zaman sorulsun?",
  "hatirlat.zamanAlt": "Vakit çıkmadan önce. Namazı kıldığını daha önce işaretlersen soru gelmez.",
  "hatirlat.dk": "{n} dk",
  "hatirlat.izin": "Bildirimlere izin ver",
  "hatirlat.izinsiz": "Bildirim olmadan devam et",
  "bugun.kalan": "{Vakit} vaktine kalan",
  "bugun.kalanSure": "{dk} dk",
  "bugun.kalanSaat": "{sa} sa {dk} dk",
  "bugun.cevapsizDun": "Dün {vakit} cevapsız kaldı. Kıldın mı?",
  "bugun.cevapsizBugun": "{Vakit} cevapsız kaldı. Kıldın mı?",
  "bugun.cevapsizTarih": "{tarih} {vakit} cevapsız kaldı. Kıldın mı?",
  "bugun.kildim": "Kıldım",
  "bugun.kilamadim": "Kılamadım",
  "bugun.kalanKaza": "Kalan kaza namazı",
  "bugun.kazaKil": "Kaza kıl",
  "bugun.kilamadimKayit": "{Vakit} kazana 1 eklendi.",
  "bugun.ozelHal": "Özel hal günüm",
  "bugun.ozelHalAlt": "Bugünün vakitleri kazaya eklenmez, seri bozulmaz.",
  "bugun.ozelHalDugme": "Özel hal",
  "bugun.hedefIlerleme": "Bugün {n} / {hedef}",
  "bugun.hedefTamam": "Bugünkü hedef tamam",
  "bugun.bitisTahmini": "Bu hızla {tarih} tamamlanır",
  "kaza.baslik": "Kaza kıl",
  "kaza.soru": "Hangi vaktin kazasını kıldın?",
  "kaza.kalan": "kalan",
  "kaza.kaydedildi": "{Vakit} kazası kaydedildi",
  "kaza.toplam": "Toplam kalan: {n}",
  "kaza.gecmis": "İşlem geçmişi",
  "kaza.bitti": "Bu vaktin kazası tamamlandı.",
  "kaza.hepsiBitti": "Kayıtlı kaza borcun tamamlandı. Allah kabul etsin.",
  "gecmis.baslik": "Geçmiş",
  "gecmis.ilkBorc": "Başlangıçtaki borç",
  "gecmis.kilinan": "Kılınan kaza",
  "gecmis.kalan": "Kalan",
  "gecmis.kazaKilindi": "{Vakit} kazası kılındı",
  "gecmis.kilinamadi": "{Vakit} kılınamadı, kazaya eklendi",
  "gecmis.manuel": "Kaza sayıları elle düzeltildi",
  "gecmis.yenidenHesap": "Başlangıç bilgileri değişti, borç yeniden hesaplandı",
  "gecmis.geriAlindi": "İşlem geri alındı: {aciklama}",
  "gecmis.bos": "Henüz bir işlem yok. Kıldığın her kaza burada görünecek.",
  "gecmis.bugun": "Bugün",
  "gecmis.dun": "Dün",
  "gecmis.buHafta": "Bu hafta kılınan",
  "gecmis.buAy": "Bu ay kılınan",
  "gecmis.orucTutuldu": "Kaza orucu tutuldu",
  "gecmis.orucDuzeltme": "Kaza orucu borcu düzeltildi",
  "gecmis.tamamlandi": "%{n} tamamlandı",
  "vakitler.baslik": "Vakitler",
  "vakitler.imsak": "İmsak",
  "vakitler.gunes": "Güneş",
  "vakitler.simdi": "Şimdi",
  "zikir.baslik": "Zikirmatik",
  "zikir.dokun": "Saymak için dokun",
  "zikir.hedef": "Hedef",
  "zikir.serbest": "Serbest",
  "zikir.sifirla": "Sıfırla",
  "zikir.sifirlaSoru": "Sayaç sıfırlansın mı?",
  "zikir.tur": "{n}. tur tamamlandı",
  "oruc.baslik": "Kaza orucu",
  "oruc.kalan": "Kalan kaza orucu",
  "oruc.gun": "{n} gün",
  "oruc.tutulan": "Tutulan",
  "oruc.toplam": "Toplam borç",
  "oruc.tuttum": "Bir gün tuttum",
  "oruc.kaydedildi": "Kaza orucu kaydedildi",
  "oruc.duzelt": "Borcu düzelt",
  "oruc.duzeltAlt": "Kaç gün kaza orucun kaldığını gir. Uygulama oruç borcunu hesaplamaz; kendi bildiğin sayıyı yaz.",
  "oruc.ekle": "Kaza orucu borcunu ekle",
  "oruc.bitti": "Kaza orucu borcun tamamlandı. Allah kabul etsin.",
  "takvim.baslik": "Takvim",
  "takvim.tam": "Beş vakit",
  "takvim.kismi": "Eksik",
  "takvim.kilinamadi": "Kılınamadı",
  "takvim.muaf": "Özel hal",
  "takvim.onceki": "Önceki ay",
  "takvim.sonraki": "Sonraki ay",
  "hadis.saatlik": "Bu saatin hadisi",
  "hadis.vakit": "{Vakit} vaktinin hadisi",
  "hadis.devami": "Devamını oku",
  "hadis.kisalt": "Kısalt",
  "hadis.kaynakNotu": "Hadis metinleri: Sahîh-i Buhârî Türkçe çevirisi, hadith-api (açık kaynak).",
  "kible.baslik": "Kıble",
  "kible.kartAlt": "Pusula ile kıble yönünü bul",
  "kible.aci": "Kıble, kuzeyden saat yönünde {aci}°",
  "kible.yonelt": "Telefonu yere paralel tut, Kâbe simgesi tepeye gelene kadar dön.",
  "kible.dogru": "Kıble yönündesin",
  "kible.pusulaYok": "Pusula bilgisi alınamadı. Kıbleyi açıya göre bulabilirsin.",
  "kible.izinGerek": "Pusula için konum izni gerekiyor. Konumun bu telefondan çıkmaz.",
  "kible.izinVer": "İzin ver",
  "kible.kalibre": "Pusula yanlış gösteriyorsa telefonu havada 8 çizerek birkaç kez çevir. Mıknatıs ve metal eşyalardan uzak dur.",
  "rozet.seri": "Vakit serisi",
  "rozet.seriGun": "{n} gün",
  "rozet.seriAlt": "Beş vaktin hepsini kıldığın art arda günler",
  "rozet.enUzun": "En uzun: {n} gün",
  "rozet.baslik": "Rozetler",
  "rozet.kazanilan": "{n} / {toplam} rozet",
  "rozet.ilkKaza": "İlk kaza",
  "rozet.kazaSayisi": "{n} kaza",
  "rozet.seriRozet": "{n} gün seri",
  "rozet.borcBitti": "Borç bitti",
  "bildirim.girisBaslik": "{Vakit} vakti girdi",
  "bildirim.girisGovde": "{Konum} için {vakit} vakti {saat}.",
  "bildirim.soruBaslik": "{Vakit} namazını kıldın mı?",
  "bildirim.soruGovde": "{Vakit} vakti {saat}'te çıkıyor.",
  "bildirim.yatsiSoruGovde": "Bugünün yatsı namazını işaretlemeyi unutma.",
  "bildirim.sonUyari": "Hatırlatmaların devam etmesi için uygulamayı bir kez aç.",
  "bildirim.dugmeKildim": "Kıldım",
  "bildirim.dugmeKilamadim": "Kılamadım",
  "bildirim.dugmeSonra": "Sonra",
  "bildirim.kanalGiris": "Vakit girdi uyarısı",
  "bildirim.kanalSoru": "Kıldın mı? soruları",
  "ayar.baslik": "Ayarlar",
  "ayar.konum": "Konum",
  "ayar.konumDegistir": "Değiştir",
  "ayar.kazaBilgileri": "Kaza başlangıç bilgileri",
  "ayar.kazaBilgileriAlt": "Değiştirirsen borç yeniden hesaplanır. Kıldığın kazalar korunur.",
  "ayar.kazaDuzelt": "Kaza sayılarını düzelt",
  "ayar.kazaDuzeltAlt": "Bir vaktin kalan sayısını elle değiştir.",
  "ayar.hedef": "Günlük kaza hedefi",
  "ayar.hedefAlt": "Her gün kaç kaza kılmayı hedefliyorsun? Bitiş tarihi buna göre tahmin edilir.",
  "ayar.hedefYok": "Yok",
  "ayar.bildirimler": "Bildirimler",
  "ayar.girisBildirimi": "Vakit girdi bildirimi",
  "ayar.girisBildirimiAlt": "Kapatırsan yalnızca \"Kıldın mı?\" sorusu gelir.",
  "ayar.soruZamani": "\"Kıldın mı?\" zamanı",
  "ayar.yatsiSaati": "Yatsı soru saati",
  "ayar.vakitDuzelt": "Vakit düzeltmeleri",
  "ayar.vakitDuzeltAlt": "Vakitler bulunduğun yerin takviminden farklıysa dakika ekle ya da çıkar.",
  "ayar.izinYok": "Bildirim izni kapalı. Hatırlatmalar gelmeyecek.",
  "ayar.izinVer": "İzin ver",
  "ayar.kesinAlarm": "Hatırlatmalar gecikebilir. \"Alarmlar ve hatırlatıcılar\" iznini aç.",
  "ayar.kesinAlarmDugme": "Ayarı aç",
  "ayar.yedekleme": "Yedekleme",
  "ayar.yedekAl": "Yedek al",
  "ayar.yedekAlAlt": "Telefon değiştirmeden önce yedeğini al ve güvenli bir yere kaydet.",
  "ayar.geriYukle": "Yedekten geri yükle",
  "ayar.reklamGizlilik": "Reklam gizlilik seçenekleri",
  "ayar.hakkinda": "Hakkında",
  "yedek.onayBaslik": "Yedek geri yüklensin mi?",
  "yedek.onayGovde": "Bu yedekte kalan kaza: {n}. Yedek tarihi: {tarih}. Mevcut verilerin yerine geçecek.",
  "yedek.onayDugme": "Geri yükle",
  "yedek.basarili": "Yedek geri yüklendi.",
  "yedek.hata": "Bu dosya Kaza Defteri yedeği değil ya da bozuk. Mevcut verilerin değişmedi.",
  "hakkinda.metin": "Kaza Defteri, kaza namazı borcunu kendi girdiğin bilgilere göre hesaplamana ve takip etmene yardımcı olur. Dini bir hüküm bildirmez. Hesaplama ve vakitlerle ilgili emin olmadığın durumlar için müftülüğe danışabilirsin.",
  "hakkinda.vakit": "Namaz vakitleri telefonunda astronomik olarak hesaplanır. Resmi takvimle birkaç dakikalık fark olabilir; Ayarlar'dan düzeltebilirsin.",
  "hakkinda.gizlilik": "Kaza ve namaz kayıtların yalnızca bu telefonda saklanır, hiçbir yere gönderilmez. Uygulama ücretsizdir ve Google AdMob aracılığıyla reklam gösterir.",
  "hakkinda.surum": "Sürüm {surum}",
} as const;

export const VAKIT_ADLARI: Record<KazaVakit, string> = {
  sabah: "Sabah",
  ogle: "Öğle",
  ikindi: "İkindi",
  aksam: "Akşam",
  yatsi: "Yatsı",
  vitir: "Vitir",
};

export type MetinAnahtari = keyof typeof METINLER;

/** Metni getirir, {alan} değişkenlerini doldurur. */
export function t(anahtar: MetinAnahtari, degiskenler?: Record<string, string | number>): string {
  const metin: string = METINLER[anahtar];
  if (!degiskenler) return metin;
  return metin.replace(/\{(\w+)\}/g, (tum, ad: string) =>
    ad in degiskenler ? String(degiskenler[ad]) : tum,
  );
}
